server:
  port: 9200
spring:
  devtools:
    livereload:
      enabled: true
  jmx:
    default-domain: know-lad
  main:
    allow-bean-definition-overriding: true
  jackson:
    default-property-inclusion: NON_NULL
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        temp:
          use_jdbc_metadata_defaults: false
    hibernate:
      ddl-auto: update
  application:
    name: know-lad
  banner:
    location: classpath:banner.txt

PROPERTY_PATH:  D:\MOOC\CaseStudy\KnowYourLad\Properties\know_lad.yml